services:
    app.repository.doctor_repository:
        class: AppBundle\Repository\DoctorRepository

    app.repository.hospital_repository:
        class: AppBundle\Repository\HospitalRepository

    app.request.param_converter.doctor_param_converter:
        class: AppBundle\Request\ParamConverter\DoctorParamConverter
        arguments:
            - "@app.repository.doctor_repository"
        tags:
            - { name: request.param_converter, converter: "doctor_param_converter" }
